### ISSUE TITLE
Continuing discussions from react-native-keyboard-spacer#71

### ISSUE THREAD

**Issue by dextermb** [ambistudio/react-native-spacer#1] opened 2018-09-12 08:44 UTC
You can test using virtual devices by using [Xcode](https://developer.apple.com/xcode/) or [android studio](https://developer.android.com/studio/). Xcode requires a mac, whereas android studio can be used anywhere.

I have tested your updated demo, I seem to be still having issues. See the attached [screenshot](https://user-images.githubusercontent.com/6137789/45413099-42e9a180-b670-11e8-8909-2cdbdb0499ef.png).

This is a Pixel 2 XL with UI scale set to max. As you can see the input is focused, but the keyboard overlaps it.

---

[Reference](https://github.com/Andr3wHur5t/react-native-keyboard-spacer/issues/71)

**Comment by hieunc229** [comment] 2018-09-12 09:31
Thanks, @dextermb. I dig a little bit into the problem, seem like it related to https://github.com/facebook/react-native/issues/15387.

In short, when `keyboardWillShow` event is triggered, the library calculate and animate the position of the`<Spacer>...</Spacer>`. Unfortunately, `keyboardWillShow` is not available on Android.

One solution could be using `keyboardDidShow` for Android instead ([see Method > addListener > Note...](https://facebook.github.io/react-native/docs/keyboard.html)). I will spend a little more time to see is there any better solution for this

**Comment by dextermb** [comment] 2018-09-12 09:43
@hieunc229 What `react-native-keyboard-spacer` does is check if the `Platform` is ios or android, then switch between event names.

As seen [here](https://github.com/Andr3wHur5t/react-native-keyboard-spacer/blob/master/KeyboardSpacer.js#L61-L68):

    const updateListener = Platform.OS === 'android' ? 'keyboardDidShow' : 'keyboardWillShow';
    const resetListener = Platform.OS === 'android' ? 'keyboardDidHide' : 'keyboardWillHide';

**Comment by hieunc229** [comment] 2018-09-12 15:09
I have updated the repo and managed to test it on a Nexus 5. [Preview on Expo Snack](https://snack.expo.io/@hieunc/react-native-spacer)

Hope it help!

**Comment by hieunc229** [comment] 2018-09-13 10:48
Since the problem is solved, I'll close this issue. Feel free to reopen when necessary!

**Closed as completed by hieunc229** 2018-09-13 10:48 UTC
